// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6AjPpHLNvojvY0TkTItAw-cFldZlWtzM',
    appId: '1:660277912808:android:d61dc39514f25f3c5c555d',
    messagingSenderId: '660277912808',
    projectId: 'seedina-app',
    databaseURL: 'https://seedina-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seedina-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh745dHUYfJKiP1MLyO77g0ksOabQZXQU',
    appId: '1:660277912808:ios:ed4a3057ad4de67c5c555d',
    messagingSenderId: '660277912808',
    projectId: 'seedina-app',
    databaseURL: 'https://seedina-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'seedina-app.firebasestorage.app',
    iosClientId: '660277912808-ue72vipi6l18g287efohgmnmch891l6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.seedina',
  );

}